#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ] && [ ! -z "$WWWGROUP" ]; then
    usermod -u $WWWUSER app
fi

if [ "$NODE_ENV" = "development" ]; then
    yarn dev
fi

if [ "$NODE_ENV" = "production" ]; then
    yarn build
    yarn start
fi