version: '3'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: next-app:latest
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3000:3000'
    environment:
      WWWGROUP: '${WWWGROUP}'
      WWWUSER: '${WWWUSER}'
      NODE_ENV: '${NODE_ENV}'
    volumes:
      - '.:/var/www/html'
    networks:
      - real-estate-backend_main

networks:
  real-estate-backend_main:
    external: true